export const theme = {
    colors: {
      primary: '#ff7f50',
      white: '#ffffff',
      gray:'#f5f5f5',
      lightPrimary:"#db9277"
    },
    fonts: ['sans-serif', 'inter', 'productSans', 'Poppins'],
    fontSizes: {
      headingOne: '56px',
      headingTwo: '48px',
      headingThree: '40px',
      headingFour: '32px',
      headingFive: '24px',
      headingSix: '20px',
      largeText: '20px',
      mediumText: '18px',
      normalText: '16px',
      smallText: '14px',
    },
    fontWeight: {
      normal: 400,
      bold: 700,
      bolder: 800,
    },
    lineHeights: {
      headingOne: '61.6px',
      headingTwo: '52.8px',
      headingThree: '44px',
      headingFour: '35.2px',
      headingFive: '26.4px',
      headingSix: '22px',
      largeText: '28px',
      mediumText: '25.2px',
      normalText: '22.4px',
      smalltext: '19.6px',
    },
    padding: {
      sm: '0.5rem',
      md: '1rem',
      xmd: '1.5rem',
      lg: '2rem',
      xlg: '3rem',
      xxlg: '4rem',
      xxxlg: '4.5rem',
    },
    margin: {
        sm: '0.5rem',
        md: '1rem',
        xmd: '1.5rem',
        lg: '2rem',
        xlg: '3rem',
        xxlg: '4rem',
        xxxlg: '4.5rem',
    },
  };
  